-- 1. New table for named AI filter profiles (per user)
create table public.ai_filter_profiles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  chatgpt_prompt text not null default '',
  blacklisted_companies text[] not null default '{}'::text[],
  is_default boolean not null default false
);

-- Enforce at most one default profile per user
create unique index ai_filter_profiles_one_default_per_user
  on public.ai_filter_profiles (user_id) where is_default;

alter table public.ai_filter_profiles enable row level security;
create policy "enable all for users based on user_id"
  on public.ai_filter_profiles
  as permissive for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 2. Link a Search (links row) to an optional profile. SET NULL on profile delete.
alter table public.links
  add column filter_profile_id bigint
  references public.ai_filter_profiles(id) on delete set null;

-- 3. Drop the now-obsolete single-prompt column. Global blacklist stays on advanced_matching.blacklisted_companies.
alter table public.advanced_matching drop column chatgpt_prompt;

-- 4. Atomic "set as default" helper: clears other defaults for the user, then sets target.
create or replace function public.set_default_filter_profile(p_id bigint)
returns void
language plpgsql
security invoker
as $$
declare
  v_user uuid := auth.uid();
begin
  update public.ai_filter_profiles set is_default = false
    where user_id = v_user and is_default and id <> p_id;
  update public.ai_filter_profiles set is_default = true
    where id = p_id and user_id = v_user;
end;
$$;
