-- Items 7/8 — per-link tailored resume + cover letter versions.
-- Spec: spec.md §5 Items 7/8.

create table if not exists public.resume_versions (
  id            bigint generated by default as identity primary key,
  profile_id    bigint null references public.ai_filter_profiles(id) on delete set null,
  link_id       bigint null references public.links(id)              on delete cascade,
  content_jsonb jsonb not null,
  model         text  not null default 'gpt-4o-mini',
  created_at    timestamptz not null default now()
);

create index if not exists resume_versions_link_idx
  on public.resume_versions (link_id, created_at desc);

create table if not exists public.cover_letter_versions (
  id            bigint generated by default as identity primary key,
  profile_id    bigint null references public.ai_filter_profiles(id) on delete set null,
  link_id       bigint null references public.links(id)              on delete cascade,
  content_jsonb jsonb not null,
  model         text  not null default 'gpt-4o-mini',
  created_at    timestamptz not null default now()
);

create index if not exists cover_letter_versions_link_idx
  on public.cover_letter_versions (link_id, created_at desc);

alter table public.resume_versions       enable row level security;
alter table public.cover_letter_versions  enable row level security;

create policy "users read tailored resume via filter profile ownership"
  on public.resume_versions for select to authenticated
  using (
    profile_id is null
    or profile_id in (select id from public.ai_filter_profiles where user_id = auth.uid())
  );

create policy "users read tailored cover letter via filter profile ownership"
  on public.cover_letter_versions for select to authenticated
  using (
    profile_id is null
    or profile_id in (select id from public.ai_filter_profiles where user_id = auth.uid())
  );
