-- Items 5/6 — keyword extraction storage.
-- Spec: spec.md §5 Items 5/6.

alter table public.links
  add column if not exists keywords_jsonb jsonb null;

-- companies table: ensure exists (referenced by link.company_id in upstream).
-- If absent, this migration creates a minimal shape and adds the keyword column.
do $$
begin
  if not exists (select 1 from information_schema.tables where table_schema='public' and table_name='companies') then
    create table public.companies (
      id bigint generated by default as identity primary key,
      created_at timestamptz not null default now(),
      name text not null unique,
      website_url text null,
      linkedin_url text null
    );
    alter table public.companies enable row level security;
    create policy "read companies" on public.companies for select to authenticated using (true);
  end if;
end$$;

alter table public.companies
  add column if not exists mission_keywords_jsonb jsonb null;
